spring.application.name=chemicalElements

server.port=8090

springdoc.swagger-ui.path=/docs

# File configuration
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB